"use strict"

function generateHelpMenu() {
    return [
        "🤖 *USERBOT FAHRI — HELP MENU*",
        "",
        "🏠 *PRIVATE CHAT*",
        "Detect Link dan seluruh downloader hanya aktif melalui private chat.",
        "Auto Reply hanya bekerja melalui private chat.",
        "Pesan grup tidak diteruskan kepada owner oleh Auto Reply Forwarder.",
        "Keyword Reply otomatis hanya bekerja di private chat.",
        "",
        "👥 *GROUP CHAT*",
        "Untuk saat ini bot di grup hanya menjalankan Anti Kasar.",
        "Auto Reply, Keyword Reply, Detect Link, downloader, media tools, dan Sticker Safety tidak merespons di grup.",
        "Edited Message Guardian tetap bekerja sebagai bagian dari perlindungan Anti Kasar bila Bot dan Anti Kasar grup aktif.",
        "",
        "📥 *DOWNLOADER — PRIVATE CHAT ONLY*",
        "Kirim link TikTok, Instagram, Threads, YouTube, Spotify, Facebook, Pinterest, atau SoundCloud melalui chat pribadi bot.",
        ".spdl <link Spotify>",
        ".spotify <link Spotify>",
        ".dlold <url> — downloader legacy explicit",
        "",
        "🧰 *MEDIA TOOLS — PRIVATE CHAT*",
        ".stiker — ubah gambar/video menjadi sticker",
        ".pdf — ubah gambar menjadi PDF",
        ".vn / .ptt — ubah audio menjadi voice note",
        ".makeqr — membuat QR art",
        ".tgstiker <link pack Telegram>",
        "",
        "🛡️ *ANTI KASAR & GROUP CONTROL*",
        ".grouplist",
        ".groupctl status <G001|group_jid>",
        ".groupctl on/off <G001|group_jid>",
        ".groupctl feature <group> antikasar on/off",
        ".antikasar status",
        ".renungctl",
        ".kasarsafe status/test/collisions",
        ".kasarocr status/test",
        "",
        "✏️ *EDITED MESSAGE GUARDIAN*",
        ".editguard status",
        ".editguard on/off",
        ".editguard set <group_jid> on/off",
        ".editguard log",
        "Pesan hasil edit hanya diperiksa oleh sistem Anti Kasar; link atau command hasil edit tidak menjalankan fitur lain.",
        "",
        "💬 *AUTO REPLY — PRIVATE CHAT ONLY*",
        ".reply on — mengaktifkan Auto Reply private",
        ".reply off — mematikan Auto Reply",
        ".reply status — melihat status dan scope",
        ".bot <status> — mengatur Custom Auto Reply",
        ".bot on/off/status",
        "",
        "👁️ *STATUS & SECURITY*",
        ".status / .statusdl",
        ".statusget",
        ".statusid",
        ".securitylog status",
        ".securitylog test",
        "",
        "⚡ *OWNER TOOLS — PRIVATE CHAT*",
        ".health",
        ".settings list",
        ".reactiontest",
        ".reactionctl status",
        ".bcstatus / .bcfail / .bcretry",
        ".backup",
        ".cleanmedia",
        "",
        "🧮 *UTILITY — PRIVATE CHAT*",
        ".calc <ekspresi>",
        ".hitung <ekspresi>",
        "cuaca <kota>",
        "",
        "ℹ️ Command owner yang dikirim di grup disenyapkan. Gunakan private chat bot.",
    ].join("\n")
}

module.exports = {
    generateHelpMenu,
}
