"use strict"

function generateHelpMenu() {
    return [
        "🤖 *USERBOT FAHRI — HELP MENU*",
        "",
        "👥 *GROUP CHAT*",
        "Saat Bot group ON, command dan fitur yang memang mendukung group tetap dapat digunakan sesuai permission dan konfigurasi masing-masing.",
        "Saat Bot group OFF, seluruh pemrosesan pesan masuk di group dihentikan.",
        "",
        "Yang khusus PRIVATE CHAT:",
        "- Detect Link otomatis dari link yang dikirim tanpa command",
        "- Auto Reply, Custom Auto Reply, dan Keyword Auto Reply",
        "",
        "Command downloader eksplisit seperti .spdl/.spotify dan .dlold tetap dapat digunakan di group aktif bila fitur Downloader group ON.",
        "Anti Kasar, Edited Message Guardian, Sticker Safety, media tools, utility, dan command menu lainnya tetap mengikuti scope/permission existing.",
        "",
        "🏠 *PRIVATE CHAT*",
        "Kirim link TikTok, Instagram, Threads, YouTube, Spotify, Facebook, Pinterest, atau SoundCloud tanpa command untuk Detect Link otomatis.",
        "Auto Reply hanya bekerja melalui private chat.",
        "Keyword Reply otomatis hanya bekerja di private chat.",
        "Notifikasi Auto Reply Forwarder dikirim ke grup notification, bukan PM owner.",
        "",
        "📥 *DOWNLOADER*",
        ".spdl <link Spotify> — command eksplisit, dapat dipakai di private/group aktif",
        ".spotify <link Spotify> — alias .spdl",
        ".dlold <url> — downloader legacy eksplisit, dapat dipakai di private/group aktif",
        "Kirim link tanpa command — private chat only",
        "",
        "🧰 *MEDIA TOOLS*",
        ".stiker — ubah gambar/video menjadi sticker",
        ".tourl — upload gambar/stiker/video menjadi link URL",
        ".pdf — ubah gambar menjadi PDF",
        ".vn / .ptt — ubah audio menjadi voice note",
        ".makeqr — membuat QR art",
        ".tgstiker <link pack Telegram>",
        "",
        "🛡️ *ANTI KASAR & GROUP CONTROL*",
        ".grouplist",
        ".groupctl status <G001|group_jid>",
        ".groupctl on/off <G001|group_jid>",
        ".groupctl feature <group> antikasar on/off",
        ".groupctl feature <group> downloader on/off",
        ".groupctl feature <group> stickersafety on/off",
        ".antikasar status",
        ".renungctl",
        ".kasarsafe status/test/collisions",
        ".kasarocr status/test/clearcache — OCR kata kasar stiker + highlight kata",
        "",
        "👋 *WELCOME & MENU INTERAKTIF GRUP*",
        ".menu / .groupmenu / .help — di grup akan membuka menu interaktif",
        ".groupinfo — informasi grup",
        ".rules — deskripsi/peraturan grup",
        ".adminlist — daftar admin grup",
        ".fiturgrup — status fitur grup",
        ".welcome status/on/off — admin grup/owner",
        ".welcome menu on/off — aktifkan menu interaktif",
        ".welcome set <pesan> — placeholder {user}, {group}, {member_count}",
        ".welcome reset / .welcome test",
        "Welcome hanya dikirim apabila Bot Grup ON, fitur Welcome ON, dan bot berstatus admin.",
        "",
        "🎮 *GAME GRUP*",
        ".quiz / .jawab <A|B|C|D>",
        ".tebakangka / .tebak <angka>",
        ".suit <batu|gunting|kertas>",
        ".truth / .dare / .coinflip / .roll",
        "",
        "🛡️ *STICKER SAFETY — GROUP + PRIVATE*",
        ".stikerguard status",
        ".stikerguard scan — reply sticker untuk melihat hasil OCR dan skor NSFW",
        ".stikerguard warmup — memuat model NSFW terlebih dahulu",
        ".stikerguard clearcache — menghapus cache hasil scan lama",
        ".stikerguard nsfw on/off",
        "Sticker statis dan animasi diperiksa untuk pornografi, hentai, ketelanjangan, dan konten seksual.",
        "",
        "✏️ *EDITED MESSAGE GUARDIAN*",
        ".editguard status",
        ".editguard on/off",
        ".editguard set <group_jid> on/off",
        ".editguard log",
        "",
        "💬 *AUTO REPLY — PRIVATE CHAT ONLY*",
        ".reply on",
        ".reply off",
        ".reply status",
        ".bot <status>",
        ".bot on/off/status",
        "Auto Reply sekarang membalas sebagai quoted/reply bubble ke pesan user dan memakai nama depan user bila tersedia.",
        "Placeholder reply yang didukung: {name}, {firstName}, dan {greeting}.",
        "",
        "🚦 *COMMAND RATE LIMIT & ANTI-SPAM*",
        ".ratelimit status",
        ".ratelimit on/off",
        ".ratelimit set command 5s",
        ".ratelimit set downloader 30s",
        ".ratelimit set media 20s",
        ".ratelimit set ocr 45s",
        ".ratelimit set max 5",
        ".ratelimit group <G001|group_jid> on/off",
        ".ratelimit top",
        ".ratelimit reset",
        "Owner tidak dibatasi. Warning spam dibatasi agar bot tidak ikut memenuhi chat.",
        "",
        "🔔 *BOT NOTIFICATION*",
        ".notifytarget status",
        ".notifytarget test",
        ".notifytarget active test",
        ".notifytarget autoreply test",
        "Target notification: 120363424006225997@g.us",
        "",
        "👁️ *STATUS & SECURITY*",
        ".status / .statusdl",
        ".statusget",
        ".statusid",
        ".securitylog status",
        ".securitylog test",
        "View Once dan Anti-Delete tetap dikirim ke target Security Media Log existing.",
        "",
        "⚡ *OWNER TOOLS — PRIVATE CHAT*",
        ".health",
        ".settings list",
        ".reactiontest",
        ".reactionctl status",
        ".bcstatus / .bcfail / .bcretry",
        ".backup",
        ".cleanmedia",
        "",
        "🧮 *UTILITY*",
        ".calc <ekspresi>",
        ".hitung <ekspresi>",
        "",
        "ℹ️ Command owner yang memang private-only tetap disenyapkan bila dikirim di group.",
    ].join("\n")
}

module.exports = {
    generateHelpMenu,
}
